# params.yaml - Configuration for House Price Prediction Pipeline

prepare:
  random_seed: 42
  dataset_path: 'data/zameen-updated.csv'

features:
  test_size: 0.2
  random_state: 42
  target_column: 'price'
  categorical_features:
    - 'city'
    - 'property_type'
    - 'purpose'
    - 'Area Type'
  numerical_features:
    - 'bedrooms'
    - 'baths'
    - 'Area Size'

train:
  model_type: 'RandomForest'  # RandomForest, GradientBoosting, or LinearRegression
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  random_state: 42

evaluate:
  metrics:
    - 'rmse'
    - 'mae'
    - 'r2_score'
